[project]
name = "pynote"
version = "0.1.1"
description = "Read the README.md file for more information"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=11.2.1",
    "pronotepy>=2.14.3",
    "tkchart>=2.1.6",
]